---
title: "Tutorial 1.3"
author: "Julia Lee"
format: html
---

```{r}
#### Preamble ####
# Purpose: Create a graph using the cleaned data
# Author: Julia Lee
# Date: 18 September 2024
# Prerequisites: Have installed the necessary package and have ran download_data.R (first) and clean_data.R (Second)
```

```{r}
#### Workspace setup ####
# install.packages("tidyverse")
# install.packages("janitor")

library(tidyverse)
library(janitor)
```

```{r}
#### Read in the data ####
cleaned_elections_data <-
  read_csv(
    file = "cleaned_canadian_elections.csv",
    show_col_types = FALSE
  )
```

```{r}
# Counting the number of seats won by each party
cleaned_elections_data |>
  count(party)
```

```{r}
# Create the graph
cleaned_elections_data |>
  ggplot(aes(x = party)) +
  geom_bar() +
  theme_minimal() + # Make the theme neater
  ggtitle("Number of Ridings Won by Each Party (2021 Canadian Federal Election)") + 
  labs(x = "Party", y = "Number of seats") # Make labels more meaningful
```

